FROM golang:1.25-alpine AS builder

#stage 1: membuat aplikasi
WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/app

#stage 2: membuat aplikasi menjadi lebih ringan 
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080

CMD [ "./main" ]